defaults:
  - arch: trm
  - _self_

hydra:
  output_subdir: null

data_paths: ['data/mnist']
data_paths_test: []

evaluators:
  - name: mnist@MNIST

global_batch_size: 16

epochs: 20
eval_interval: 1
checkpoint_every_eval: True

lr: 1e-4
lr_min_ratio: 0.1
lr_warmup_steps: 500

beta1: 0.9
beta2: 0.95
weight_decay: 0.1
puzzle_emb_weight_decay: 0.1

puzzle_emb_lr: 1e-3

seed: 0
min_eval_interval: 0

project_name: MNIST-ACT-torch
arch:
  loss:
    loss_type: mnist_class_cross_entropy
    depth_diversity_coef: 0.01
  forward_dtype: float32
  mlp_t: True
  hidden_size: 64
  num_heads: 2
  expansion: 2
  puzzle_emb_ndim: 0
  puzzle_emb_len: 0
  H_cycles: 1
  L_cycles: 1
  L_layers: 1
  halt_max_steps: 4
  halt_exploration_prob: 0.0
  force_fixed_halt_steps: True
  use_depth_step_embedding: True
  depth_step_embedding_scale: 1.0

ema: False
ema_rate: 0.999
freeze_weights: False